#!/usr/bin/env python3

# this script is written explicitly to work along with this vscode extension:
# https://marketplace.visualstudio.com/items?itemName=augustocdias.tasks-shell-input
# https://github.com/augustocdias/vscode-shell-command

# we use this script as a command to populate the list of serial ports available on the system
# we use python, because we know this is already present for qorc-sdk (source envsetup.sh) AND
# the pySerial module is also installed by default.

# the extension expects each line of the stdout of this "command" to look like this:
# "VALUE|SOMETHING|SOMETHING|SOMETHING..."
# then, the "VALUE" is input provided, and SOMETHING(s) are used to display 
# descriptive text in the dropdown generated by the extension in vscode

# so, we pass in 'N' lines, each line corresponding to a serial port found,
# with the format of each line as:
# "PORT|PORT|DESCRIPTION|HARDWAREID"
# why PORT 2 times?
# the VALUE in the format is passed into the input, but NOT displayed in the drop down
# In our case, we want to display the PORT as well -> it is easier for the user
# so the 2nd PORT is for display purposes.
# tested on Linux only, though should work for Windows I suppose.


import serial.tools.list_ports
#import inspect

#print(inspect.getfile(serial.tools.list_ports))
#print(inspect.getfile(inspect))

ports = serial.tools.list_ports.comports(include_links=False)

for port, desc, hwid, in ports :
    print(port + "|" + port + "|" + desc + "|" + hwid)

