BINS = qf_person_detection/GCC_Project/output/bin/qf_person_detection.bin 

all:	$(BINS)

clean:
	cd qf_person_detection/GCC_Project && make clean




qf_person_detection/GCC_Project/output/bin/qf_person_detection.bin:
	cd qf_person_detection/GCC_Project && make

