BINS = qf_person_detect/GCC_Project/output/bin/qf_person_detect.bin 

all:	$(BINS)

clean:
	cd qf_person_detect/GCC_Project && make clean




qf_person_detect/GCC_Project/output/bin/qf_person_detect.bin:
	cd qf_person_detect/GCC_Project && make

