/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/qf_tfl/qf_person_detection/GCC_Project/output/s3x_clock.o: \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/qf_tfl/qf_person_detection/GCC_Project/../../../Libraries/Power/src/s3x_clock.c \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/qf_tfl/qf_person_detection/inc/Fw_global_config.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/HAL/inc/eoss3_dev.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/Libraries/CMSIS/inc/core_cm4.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/Libraries/CMSIS/inc/core_cmInstr.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/Libraries/CMSIS/inc/core_cmFunc.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/Libraries/CMSIS/inc/core_cm4_simd.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/HAL/inc/eoss3_hal_gpio.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/HAL/inc/eoss3_hal_def.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/Libraries/Utils/inc/common.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/HAL/inc/test_types.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/Libraries/Power/inc/s3x_clock.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/include/FreeRTOS.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/qf_tfl/qf_person_detection/inc/FreeRTOSConfig.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/qf_tfl/qf_person_detection/inc/Fw_global_config.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/include/projdefs.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/include/portable.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/include/deprecated_definitions.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/portable/GCC/ARM_CM4F_quicklogic_s3XX/portmacro.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/include/mpu_wrappers.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/include/semphr.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/include/queue.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/include/task.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/include/list.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/include/task.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/HAL/inc/test_types.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/Libraries/Power/inc/s3x_err_base.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/HAL/inc/s3x_clock_hal.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/HAL/inc/eoss3_dev.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/qf_tfl/qf_person_detection/inc/s3x_pwrcfg.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/Libraries/Power/inc/s3x_dfs.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/Libraries/Power/inc/s3x_pi.h \
 /mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/Libraries/Power/inc/s3x_err_base.h

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/qf_tfl/qf_person_detection/inc/Fw_global_config.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/HAL/inc/eoss3_dev.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/Libraries/CMSIS/inc/core_cm4.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/Libraries/CMSIS/inc/core_cmInstr.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/Libraries/CMSIS/inc/core_cmFunc.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/Libraries/CMSIS/inc/core_cm4_simd.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/HAL/inc/eoss3_hal_gpio.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/HAL/inc/eoss3_hal_def.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/Libraries/Utils/inc/common.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/HAL/inc/test_types.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/Libraries/Power/inc/s3x_clock.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/include/FreeRTOS.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/qf_tfl/qf_person_detection/inc/FreeRTOSConfig.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/qf_tfl/qf_person_detection/inc/Fw_global_config.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/include/projdefs.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/include/portable.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/include/deprecated_definitions.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/portable/GCC/ARM_CM4F_quicklogic_s3XX/portmacro.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/include/mpu_wrappers.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/include/semphr.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/include/queue.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/include/task.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/include/list.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/FreeRTOS/include/task.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/HAL/inc/test_types.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/Libraries/Power/inc/s3x_err_base.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/HAL/inc/s3x_clock_hal.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/HAL/inc/eoss3_dev.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/qf_tfl/qf_person_detection/inc/s3x_pwrcfg.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/Libraries/Power/inc/s3x_dfs.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/Libraries/Power/inc/s3x_pi.h:

/mnt/c/Users/saxe/Documents/ActiveProjects/qork-sdk-tfl/Libraries/Power/inc/s3x_err_base.h:
