/*==========================================================
 * Copyright 2020 QuickLogic Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *==========================================================*/

/** @file fpga_loader.h
 *  @brief FPGA Loader API Header
 *
 *  This header contains the function prototypes 
 *  for the FPGA Loader Library, which exposes the public
 *  API that can be used by any M4 application code.
  *
 *  @author Quicklogic Corp.
 *  @date 13 Nov 2020
 */


/**
 * @brief Loads FPGA bitstream into the EOS S3 FPGA
 * 
 * The FPGA bitstream is described by an array of 32-bit words
 * generated by the FPGA tooling, which is used by this API to
 * configure the FPGA on the EOS S3
 * 
 * @param img_size Size of the FPGA bitstream in bytes
 * @param image_ptr The FPGA bitstream array generated by the FPGA tooling
 */ 
int load_fpga(uint32_t img_size,uint32_t* image_ptr);

/**
 * @brief Loads FPGA bitstream into the EOS S3 FPGA and
 *        initializes the RAM Blocks in the FPGA
 * 
 * The FPGA bitstream is described by an array of 32-bit words
 * generated by the FPGA tooling, which is used by this API to
 * configure the FPGA on the EOS S3.
 * The RAM Block initialization values is described by an array
 * of 32-bit words with a specific format, this is also generated
 * by the FPGA tooling.
 * This API uses the initialization array to init the values of the
 * RAM Block memory cell after FPGA configuration is done.
 * 
 * @param image_size Size of the FPGA bitstream in bytes
 * @param image_ptr The FPGA bitstream array generated by the FPGA tooling
 * @param mem_content_size Size of the FPGA RAM Block Initialization Array in bytes
 * @param mem_content_ptr the FPGA RAM Block Initialization Array generated by the FPGA tooling.
 */ 
int load_fpga_with_mem_init(uint32_t image_size, uint32_t* image_ptr, uint32_t mem_content_size, uint32_t* mem_content_ptr);



